apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.django.appName }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "gce-ingress-static-ip"  # Changed from regional to global
    networking.gke.io/managed-certificates: "gce-openssl-cert"  # Updated certificate annotation
    kubernetes.io/ingress.allow-http: "false"  # Force HTTPS only
    networking.gke.io/v1beta1.FrontendConfig: "ssl-redirect"  # Ensures SSL redirect
spec:
  rules:
  - host: {{ .Values.django.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.django.appName }}
            port:
              number: 80
