global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: api-v2.integration-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-stage/bo-main/12-12-2024_18-46-19
    tag: latest
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1
