name: Deploy Backend Application and Configuration

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: bo-stage
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials demo-cluster --region asia-south1 --project bo-stage

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # - name: Install Helm
      #   run: |
      #     curl -fsSL https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -o helm.tar.gz
      #     tar -zxvf helm.tar.gz
      #     sudo mv linux-amd64/helm /usr/local/bin/helm
      #     helm version

      - name: Deploy Backend Application
        run: |
          helm upgrade --install backend-application ./application
