name: Deploy Backend Application and Configuration

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/install.yml
    secrets: inherit
    
  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: bo-stage
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/bo-stage/bo-backend-django:latest .
          docker push asia-south1-docker.pkg.dev/bo-stage/bo-backend-django:latest

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials demo-cluster --region asia-south1 --project bo-stage

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install backend-application ./application
