name: Deploy Backend Application and Configuration

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: bo-stage
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials demo-cluster --region asia-south1 --project bo-stage

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy Backend Application
        run: |
          # Get the current revision number
          CURRENT_REVISION=$(helm history backend-application -o json | jq -r '.[-1].revision')
          
          # Attempt to upgrade or install the application
          if ! helm upgrade --install backend-application ./application; then
            echo "Deployment failed. Rolling back to previous revision."
            
            # If it's a new installation (no previous revision), uninstall
            if [ -z "$CURRENT_REVISION" ]; then
              helm uninstall backend-application
            else
              # Otherwise, rollback to the previous revision
              helm rollback backend-application $CURRENT_REVISION
            fi
            
            # Exit with an error code
            exit 1
          fi

      - name: Verify Deployment
        run: |
          # Wait for the deployment to be ready
          kubectl rollout status deployment/backend-application

          # Check if the deployment is successful
          if [ $? -ne 0 ]; then
            echo "Deployment verification failed. Rolling back."
            helm rollback backend-application
            exit 1
          fi

      - name: Cleanup on Failure
        if: failure()
        run: |
          echo "Deployment failed. Ensuring rollback has occurred."
          helm history backend-application
          echo "Current revision after potential rollback:"
          helm list | grep backend-application
