name: Deploy to GKE  

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: bo-stage
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials autopilot-bo-cluster --region asia-south1 --project bo-stage

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Install Helm
        run: |
          curl -fsSL https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -o helm.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Create Static IP
        run: |
          gcloud compute addresses create gce-ingress-static-ip --global || true
          
      - name: Create ManagedCertificate
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: networking.gke.io/v1
          kind: ManagedCertificate
          metadata:
            name: gce-openssl-cert
          spec:
            domains:
              - api-v2.integration-betteropinions.com
          EOF

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install django-env ./configuration 
          helm upgrade --install backend-application ./application
          helm upgrade --install django-ingress ./ingress
          helm upgrade --install django-hpa ./autoscalling
