name: Run All Deployments

on:
  workflow_dispatch:

jobs:
  run-install:
    uses: ./.github/workflows/install.yml
    secrets: inherit

  run-rabbit:
    needs: run-install
    uses: ./.github/workflows/rabbit.yml
    secrets: inherit

  run-redis:
    needs: run-rabbit
    uses: ./.github/workflows/redis.yml
    secrets: inherit

  run-env-secret:
    needs: run-redis
    uses: ./.github/workflows/env-secret.yml
    secrets: inherit

  run-certify:
    needs: run-env-secret
    uses: ./.github/workflows/certify.yml
    secrets: inherit

  run-django-application:
    needs: run-certify
    uses: ./.github/workflows/django-application.yml
    secrets: inherit

  run-hpa:
    needs: run-django-application
    uses: ./.github/workflows/hpa.yml
    secrets: inherit
