name: Run All Workflows

on:
  workflow_dispatch:  # This allows manual triggering
  # You can add other triggers as needed

jobs:
  run_install:
    uses: ./.github/workflows/install.yml

  run_redis:
    needs: run_install
    uses: ./.github/workflows/redis.yml

  run_rabbit:
    needs: run_redis
    uses: ./.github/workflows/rabbit.yml

  run_certify:
    needs: run_rabbit
    uses: ./.github/workflows/certify.yml

  run_env_secret:
    needs: run_certify
    uses: ./.github/workflows/env-secret.yml

  run_django_application:
    needs: run_env_secret
    uses: ./.github/workflows/django-application.yml

  run_hpa:
    needs: run_django_application
    uses: ./.github/workflows/hpa.yml
