name: Run All Deployments

on:
  workflow_dispatch:

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Install and Setup
        uses: ./.github/workflows/install.yml

      - name: Deploy RabbitMQ
        uses: ./.github/workflows/rabbit.yml

      - name: Deploy Redis
        uses: ./.github/workflows/redis.yml

      - name: Deploy Django Environment and Secrets
        uses: ./.github/workflows/env-secret.yml

      - name: Deploy Certificates and Ingress
        uses: ./.github/workflows/certify.yml

      - name: Deploy Backend Application and Configuration
        uses: ./.github/workflows/django-application.yml

      - name: Deploy Django HPA
        uses: ./.github/workflows/hpa.yml
